/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panels;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parra
 */
public class RnpInfoVulnerabilidad extends javax.swing.JPanel {

    DefaultTableModel modelo;
    public RnpInfoVulnerabilidad() {
        initComponents();
        redSoporteTxt.setVisible(false);
        modelo = (DefaultTableModel) tabla.getModel();
        totalSesionesTxt.setVisible(false);
        jLabel7.setVisible(false);
        txtContactoRedSoporte.setVisible(false);
        lbTituloContactoRedsoporte.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        s = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        condicionMigratoriaCombo = new rojerusan.RSComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        discapacidadTxt = new javax.swing.JTextArea();
        redCheck = new rojerusan.RSCheckBox();
        redSoporteTxt = new RSComponentShade.RSTextFieldShade();
        jLabel7 = new javax.swing.JLabel();
        totalSesionesTxt = new RSComponentShade.RSTextFieldShade();
        grupoVulnerableCombo = new rojerusan.RSComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new rojerusan.RSTableMetro();
        jSeparator1 = new javax.swing.JSeparator();
        txtContactoRedSoporte = new RSComponentShade.RSTextFieldShade();
        lbTituloContactoRedsoporte = new javax.swing.JLabel();
        lbTituloContactoRedsoporte1 = new javax.swing.JLabel();

        Eliminar.setText("Eliminar Grupo Vulnerable");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popUp.add(Eliminar);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Vulnerabilidad", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Condición Migratoria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Pertenece a algún grupo Vulnerable?");

        s.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        s.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        s.setText("Observaciones de Grupos Vulnerables");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("¿Pertenece a una red de Soporte?");

        discapacidadTxt.setColumns(20);
        discapacidadTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        discapacidadTxt.setLineWrap(true);
        discapacidadTxt.setRows(3);
        jScrollPane1.setViewportView(discapacidadTxt);

        redCheck.setForeground(new java.awt.Color(0, 0, 0));
        redCheck.setText("SI, quiero especificar.");
        redCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                redCheckItemStateChanged(evt);
            }
        });
        redCheck.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redCheckStateChanged(evt);
            }
        });

        redSoporteTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        redSoporteTxt.setBgShadeHover(new java.awt.Color(0, 0, 0));
        redSoporteTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        redSoporteTxt.setPlaceholder("Especificar(Opcional)");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total de Sesiones");

        totalSesionesTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalSesionesTxt.setText("0");
        totalSesionesTxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        totalSesionesTxt.setPlaceholder("");

        grupoVulnerableCombo.setDisabledIdex("");
        grupoVulnerableCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                grupoVulnerableComboItemStateChanged(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons8_add_32px.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grupos Vulnerables", "-"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setBackgoundHead(new java.awt.Color(0, 102, 102));
        tabla.setBackgoundHover(new java.awt.Color(0, 102, 102));
        tabla.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tabla.setColorSecondary(new java.awt.Color(255, 255, 255));
        tabla.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tabla.setComponentPopupMenu(popUp);
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tabla.setShowGrid(true);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setMinWidth(50);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(50);
            tabla.getColumnModel().getColumn(1).setMaxWidth(50);
        }

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        txtContactoRedSoporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContactoRedSoporte.setBgShadeHover(new java.awt.Color(0, 0, 0));
        txtContactoRedSoporte.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtContactoRedSoporte.setPlaceholder("Especificar(Opcional)");

        lbTituloContactoRedsoporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTituloContactoRedsoporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloContactoRedsoporte.setText("Contacto de red Soporte");

        lbTituloContactoRedsoporte1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTituloContactoRedsoporte1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloContactoRedsoporte1.setText("(En caso de omitir la Opción \"SI\", se considerará que no pertenece a una red de soporte)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(redCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(redSoporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtContactoRedSoporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTituloContactoRedsoporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbTituloContactoRedsoporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(s, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                                        .addGap(21, 21, 21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(condicionMigratoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(grupoVulnerableCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalSesionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(grupoVulnerableCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(condicionMigratoriaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(s)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(lbTituloContactoRedsoporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(redCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTituloContactoRedsoporte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redSoporteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactoRedSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalSesionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void redCheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redCheckStateChanged
     
    }//GEN-LAST:event_redCheckStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String add = grupoVulnerableCombo.getSelectedItem().toString();
        boolean llave=false;
        
        for(int i=0; i<modelo.getRowCount(); i++){
            if(tabla.getValueAt(i, 0).toString().equals(add)){
                llave=true;
                break;
            }
        }
        if(llave==false){
            modelo.addRow(new Object[]{add});
        }else{
            JOptionPane.showMessageDialog(null, "Valor ya se encuentra registrado para el paciente");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       int valor = tabla.getSelectedRow();
       if(valor>=0){
           modelo.removeRow(valor);
       }else{
           JOptionPane.showMessageDialog(null, "Debe seleccionar un valor en la tabla para elimianar");
       }
    }//GEN-LAST:event_EliminarActionPerformed

    private void redCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_redCheckItemStateChanged
    redSoporteTxt.setVisible(redCheck.isSelected());
    txtContactoRedSoporte.setVisible(redCheck.isSelected());
    lbTituloContactoRedsoporte.setVisible(redCheck.isSelected());
    
    }//GEN-LAST:event_redCheckItemStateChanged

    private void grupoVulnerableComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_grupoVulnerableComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_grupoVulnerableComboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Eliminar;
    public rojerusan.RSComboBox condicionMigratoriaCombo;
    public javax.swing.JTextArea discapacidadTxt;
    public rojerusan.RSComboBox grupoVulnerableCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lbTituloContactoRedsoporte;
    public static javax.swing.JLabel lbTituloContactoRedsoporte1;
    private javax.swing.JPopupMenu popUp;
    public rojerusan.RSCheckBox redCheck;
    public RSComponentShade.RSTextFieldShade redSoporteTxt;
    private javax.swing.JLabel s;
    public static rojerusan.RSTableMetro tabla;
    public static RSComponentShade.RSTextFieldShade totalSesionesTxt;
    public RSComponentShade.RSTextFieldShade txtContactoRedSoporte;
    // End of variables declaration//GEN-END:variables

public static String validar(){
    String resultado="";
    totalSesionesTxt.setVisible(false);
        jLabel7.setVisible(false);
    return resultado="";
}

}
